name: Build and publish Javadoc

on: push

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build javadoc
        run: ./gradlew clean build javadoc --scan
      - name: Upload javadocs as artifact
        run: zip -r javadoc.zip ./build/docs/javadoc
      - uses: actions/upload-artifact@v4
        with:
          name: libJavadoc
          path: javadoc.zip
          if-no-files-found: warn
          overwrite: true
